# Generated by Django 2.2 on 2020-05-18 18:40

from django.db import migrations


def forwards(apps, schema):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('first_name', 'last_name').iterator():
        student.first_name = str(student.first_name).lower().capitalize()
        student.last_name = str(student.last_name).lower().capitalize()
        student.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_phone'),
    ]

    operations = [
    ]
