# Generated by Django 2.2 on 2020-05-18 18:34

from django.db import migrations


def forwards(apps, schema):
    Teacher = apps.get_model('teachers', 'Teacher')
    for teacher in Teacher.objects.all().only('first_name', 'last_name').iterator():
        teacher.first_name = str(teacher.first_name).lower().capitalize()
        teacher.last_name = str(teacher.last_name).lower().capitalize()
        teacher.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
