# Generated by Django 2.2 on 2020-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=256)),
                ('execution_time', models.DecimalField(decimal_places=4, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
