# Generated by Django 2.2 on 2020-05-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('faculty', models.CharField(max_length=64)),
                ('univesity_name', models.CharField(max_length=64)),
            ],
        ),
    ]
