# Generated by Django 2.2 on 2020-05-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='univesity_name',
            new_name='university_name',
        ),
    ]
