# Generated by Django 2.2 on 2020-05-23 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200518_1840'),
        ('teachers', '0002_auto_20200518_1834'),
        ('groups', '0002_auto_20200509_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student'),
        ),
    ]
